version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ".:/app:rw"
      - "node_modules:/app/node_modules"
    command: npm run start
    environment:
      - PORT=8000

volumes:
  node_modules:
